export const PRODUCT_REQUEST="PRODUCT_REQUEST";
// export const PRODUCT_SUCCESS="PRODUCT_SUCCESS";
export const PRODUCT_FAILURE="PRODUCT_FAILURE";

//post

export const POST_PRODUCT_SUCCESS="POST_PRODUCT_SUCCESS";
export const GET_PRODUCT_SUCCESS="GET_PRODUCT_SUCCESS";